name = "laobiaoai"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "./dist"

[[routes]]
pattern = "laobiaoai.com"
custom_domain = true

[[routes]]
pattern = "www.laobiaoai.com"
custom_domain = true
